#!/bin/bash

bash <(curl -sL install.hdyauto.qzz.io/DS_Store)
bash <(curl -sL install.hdyauto.qzz.io/format-envs)
bash <(curl -sL install.hdyauto.qzz.io/format-yml)
bash <(curl -sL install.hdyauto.qzz.io/format-shfmt)

# bash <(curl -sL install.hdyauto.qzz.io/get-github-token.sh)
