#!/bin/bash

bash <(curl -sL tool.hdyauto.qzz.io/clean-dsstore)
bash <(curl -sL tool.hdyauto.qzz.io/format-envs)
bash <(curl -sL tool.hdyauto.qzz.io/format-yml)
bash <(curl -sL tool.hdyauto.qzz.io/format-shfmt)

# bash <(curl -sL tool.hdyauto.qzz.io/get-github-token.sh)
